name: 下载、打包并上传 Docker 镜像到 GitHub Actions

on:
  push:
    branches:
      - master  # 根据需要更改触发分支

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 拉取并优化 Docker 镜像
        run: |
          docker pull raymii/qt:5.15-android-source
          docker tag raymii/qt:5.15-android-source yourusername/optimized-qt:5.15-android-source
          docker build --squash -t yourusername/optimized-qt:5.15-android-source .
          docker push yourusername/optimized-qt:5.15-android-source

      - name: 打包并压缩 Docker 镜像
        run: |
          docker pull yourusername/optimized-qt:5.15-android-source
          docker save yourusername/optimized-qt:5.15-android-source | gzip > /tmp/optimized-qt.tar.gz

      - name: 上传压缩后的 Docker 镜像到 GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: optimized-qt.tar.gz
          path: /tmp/optimized-qt.tar.gz